# Generated by Django 5.0.3 on 2024-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(upload_to='covers/')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
